### ISSUE TITLE
Lazy way of setting pauses

### ISSUE THREAD

**Issue by sebelk** [mfontanini/presenterm#105]
Hi, I've recenly discovered presenterm and I like it :)

However I'd like that there I would like adding pauses between list items to be less cumbersome, somewhat like:

intrementalmode: true

in global configuration, per presentation or per slide. Let's assume that you have some slides with 4 or five items, it's a bit annoying I to have to put a tag for each item in a list.

What do you think?

**Comment by mfontanini** [comment]
I like the idea! I'll implement it soon, it shouldn't be too complicated. Would doing this per slide only be enough for you?

**Comment by mfontanini** [comment]
I just pushed this in branch `automatic-list-pauses`. Could you try it out and see if it works for you? This is per slide and you can enable it by using a comment command like `<!-- incremental_lists: true -->`.

**Comment by sebelk** [comment]
@mfontanini Thanks! It works like a charm. It would be great if this feature could be incorporated in the the master branch. 
Ideally, it would be great to set a default value for all presentations, whether true or false, and then customize the behavior for each slide individually within the file.

Greetings

**Comment by mfontanini** [comment]
Great! I'll add something to make this work globally as well but for now at least this simplifies your life a bit.

**Comment by mfontanini** [comment]
Alright the changes I just merged to master from #109 allow setting this globally. See the example in that PR for more info.
