### ISSUE TITLE
On windows slides seems to only go to odd pages

### ISSUE THREAD

**Issue by prabirshrestha** [mfontanini/presenterm#114]
Using right arrow or left arrow to navigate seems to only go to the main slide and odd number of slides.

**Comment by mfontanini** [comment]
Can you tell me which version of windows, which terminal and which version of presenterm you're using?

**Comment by nagromc** [comment]
Same problem here. More precisely, you can see _presenterm_ showing briefly the even slides. And based on observation, it seems _presenterm_ show the next slide on button down **and** button up events.

I can provide a screen video if needed.

Environment:
- Windows 10 21H2 (19044.3803)
- Windows Terminal v1.18.231114001
- PowerShell Core v7.4.0
- presenterm v0.4.1

**Comment by mfontanini** [comment]
Thanks for the info @nagromc! I just fixed this on #119.

**Comment by prabirshrestha** [comment]
I can verify this work. Thanks for the quick fix!
