### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by syvanpera** [mfontanini/presenterm#12]
Is there any way to set the background color to either be transparent or use "none" as background color so it would automatically just use the background color defined for the terminal?

**Comment by syvanpera** [comment]
Hmm, actually now that I changed the background color to be the same as I had in my terminal (kitty), it is using the transparency. Strange

**Comment by syvanpera** [comment]
While on the subject of transparency, is there any way of defining the embedded image background as transparent. I'm using tmux and when using it, the image is displayed as a block image (so the same you would get with `viu -b xxxx.jpg`. And the same thing as with viu, the transparent background doesn't work properly unless you provide the -t parameter to viu. Any way of achieving the same here?

**Comment by syvanpera** [comment]
Ah, this is actually possible just by adding `transparent: true` to the `viuer::Config`
I'll just go ahead and close this issue as now everything seems to work

**Comment by mfontanini** [comment]
Colors are optional so if the theme doesn't set it, no background color will be used. The built in themes do have a background color tho so you either need to create a new theme without a `default.colors.background` or override that manually ok the presentation (see docs on themes). If you find value in having a no-color background theme, feel free to create a PR to add it in the themes directory. The issue with those IMO is you need to guess the foreground color to use as depending on what the user uses on their terminal it may not be very visible.

As for the images that's weird, they seem to have transparent background to me (see screenshots in README). Was this when running the demo presentation or some other one? It may be worth letting the user control that viuer transparency flag (or set it on by default, not sure if that'd break some case).

**Comment by syvanpera** [comment]
I tried not setting the background color, but for some reason on some slides on the demo presentation the background color changes to the background color of the code blocks. Which is strange. 
And regarding the image: if you don't use tmux with kitty, it will show the image correctly with transparent background. But if you use tmux it will show the image with the "blocky" characters and then the background is a checkerboard unless you specify that "transparent: true". But I agree, the transparency should be something you can set for example in the theme by setting
```
image:
  transparency: true
```
or something like that
