### ISSUE TITLE
Hard to see shell-code output with default dark theme

### ISSUE THREAD

**Issue by ketchupfriend** [mfontanini/presenterm#121]
I'm thinking this likely has to do with my terminal colours, but would be good to confirm.

Basically, the text output here is light grey on a darker grey background. I'm not sure why it's so light, since it's even harder to see than comment text on my presentation.

<img width="1993" alt="Screenshot 2024-01-08 at 18 47 01" src="https://github.com/mfontanini/presenterm/assets/146660173/9d24936e-7e28-4a57-8cfa-1907f260645f">

I'd like to know:
- What colour is being used here (is it from the terminal palette?)
- Is there any workaround? Is there an actual problem with the dark theme palette?

**Comment by mfontanini** [comment]
Thanks for the report! This should be fixed in master, can you double check? The foreground color in built-in themes wasn't being set so it would default to something... I'm not sure what. Let me know if it doesn't work tho, as I could't reproduce locally.

**Comment by ketchupfriend** [comment]
Yes, confirmed on latest master. Appreciate the prompt response!
