### ISSUE TITLE
Include the docs, examples, themes in the released binary on github

### ISSUE THREAD

**Issue by m040601** [mfontanini/presenterm#125]
Thanks for your work on this interesting tool.
I'm using it on Archlinux, using a "recipe", https://aur.archlinux.org/packages/presenterm-bin that uses the released tar.gz on github.

Currently the contents of that tar.gz include,

```
   $ tar tf presenterm-0.4.1-aarch64-unknown-linux-gnu.tar.gz
   presenterm-0.4.1/
   presenterm-0.4.1/presenterm
   presenterm-0.4.1/LICENSE
   presenterm-0.4.1/README.md
```

That's very little.
You also have much more,

```
$ ls presenterm/

assets  build.rs    Cargo.toml    docs      flake.lock  LICENSE    rustfmt.toml  src
bat     Cargo.lock  CHANGELOG.md  examples  flake.nix   README.md  scripts       themes
```

```
$ ls presenterm/docs/

config.md  highlighting.md  install.md  intro.md  latex.md  layouts.md  parse.md  pdf-export.md  README.md  themes.md

$ ls presenterm/examples/

demo.md  doge.png

$ ls presenterm/themes/

dark.yaml  light.yaml  terminal-dark.yaml  terminal-light.yaml  tokyonight-storm.yaml

```

These are very usefull.I like to have them locally on my PC, without the need to go to the Internet again.
Please include the content of that "docs", "examples", "themes" etc, folders in the released tar.gz.
Also the CHANGELOG.

Thanks in advance.

**Comment by mfontanini** [comment]
I'm not sure what you'd put in packages besides what's already there. The markdown docs here have a lot of absolute path references (e.g. `/docs/something.md`) so that may break. Not sure if it's worth adding this if you lose the ability to navigate them. Also things like `themes` should probably not be there as those are baked into the final binary so at most you could use them as examples.

I'm not very sold on the "without the internet" here, if you do really want all of those files you can clone the git repo once and have it locally forever :shrug:.

cc @pwnwriter

**Comment by pwnwriter** [comment]
I agree @mfontanini, 

I don't think we need so much clutter with just the package. We could have added a man page for `presenterm`, but there's not much going on literally. You can basically get an idea with just the help menu. And after that, the docs available online are pretty much enough.

> @m040601;  without the internet

OoO

**Comment by prabirshrestha** [comment]
Also, worth looking at how Wezterm ships 947 themes with it. https://wezfurlong.org/wezterm/colorschemes/index.html. This makes it easy to share theme.

Now that there is an index slide popup, probably worth having similar concept for selecting themes. Based on the type of the screen that is getting projected or dark/light room the theme news to be tweaked.

Cloud also ship the tutorial demo with the binary and add support for base64 encoded image so everything can be shipped in a single file.

**Comment by mfontanini** [comment]
Themes are a single yaml file, that should be simple enough to share I think? 

> probably worth having similar concept for selecting themes

You can already test themes by running with `--theme`. I also think you should know what theme you're going to use before you present, as things like images need a specific theme (e.g. dark vs light themes require different image color palettes), so I don't think there's enough value added here consider the amount of effort it will take to implement it. At least not until there's enough themes to make it worth it.

> Cloud also ship the tutorial demo with the binary and add support for base64 encoded image so everything can be shipped in a single file.

If you went ahead all the way and got to install the tool, I imagine you've spent enough effort that you can also clone the repo/download the demo presentation.

**Comment by mfontanini** [comment]
Closing this. You can always clone the repo to see the docs/other resources so packaging them seems redundant.
