### ISSUE TITLE
difficult to see the current selected slide

### ISSUE THREAD

**Issue by prabirshrestha** [mfontanini/presenterm#130]
I can barely see the bold in Windows with Wezterm. Might be use the same color as the heading (orange)?

![image](https://github.com/mfontanini/presenterm/assets/287744/06426f91-8347-4ad7-bea7-00fa4b9cba4c)

**Comment by mfontanini** [comment]
Yep, absolutely. I was planning on adding a custom theme thing for this so you can have a different color for the selected line. I have a couple of things to get to but I should be on this soon.
