### ISSUE TITLE
allow to expose current slide via webbrowser

### ISSUE THREAD

**Issue by prabirshrestha** [mfontanini/presenterm#131]
While I'm presenting, I would like others in the talk to be able to see the slide on their machine so they can copy paste scripts/code content. 

Few additional features that could be implemented in the future.
* Another addition would be to have them allow to go to previous slides but not future slides.
* This could also solve the speaker notes issue? https://github.com/mfontanini/presenterm/issues/112
* Password protection.
* Remote control slides from phone
* Share presentations as docker images
* Existing tunneling apps could be use to share the localhost server to the public. https://github.com/anderspitman/awesome-tunneling

Here is an example of terminal rendering in the browser.

![image](https://github.com/mfontanini/presenterm/assets/287744/25751746-052d-40e6-be52-05b6a7771860)

https://papigers.github.io/rutty/

Here is another one. https://github.com/btwiuse/wetty.

Wondering if these can be built in to presenterm.

**Comment by mfontanini** [comment]
This:
1. Is a ton of work.
2. Goes against how [presentations should be](https://www.youtube.com/watch?v=Unzc731iCUY). If you're presenting, you don't want people copying/pasting code, going back slides, etc. They need to be paying attention to you while you present.

Therefore, if this was a tiny feature I'd probably be okay with implementing it. But given it's a lot of work and it allows "mispresenting" I won't implement it. You may already be able to use rutty directly for this though, you should have a look.
