### ISSUE TITLE
Pauses in numbered lists reset numbering

### ISSUE THREAD

**Issue by boulanlo** [mfontanini/presenterm#15]
With the following markdown:

```markdown
Hello!
---

1. One
<!-- pause -->
2. Two
<!-- pause -->
3. Three
4. Four
```

As slides are navigated, the numbers for the list items get reset to 1 after each pause:

```
Hello!
             1. One
             1. Two
             1. Three
             2. Four
```

Tested with `presenterm` version 0.2.0 (commit da0dd9eb3a748b42b27258919a38ac420911e893), although I don't think newer versions have fixed it, judging from the commits since then.

**Comment by mfontanini** [comment]
Thanks for the report! Lists need to be a bit smarter. What's happening here is at the markdown level those _are_ different lists so for the markdown parser the numbers should actually reset. The lists need to be a bit more independent of the markdown and instead do the numbering themselves. I'll get to this soon!

**Comment by mfontanini** [comment]
@boulanlo this is fixed in master, can you double check? The solution was quite crappy and I hope I checked for all edge cases but I may have missed some.

**Comment by boulanlo** [comment]
My use case wasn't too complicated, basically what I put in the example. Looks like it's fixed for me on the latest commit :+1: thanks for your hard work!
