### ISSUE TITLE
Front matter block causing error on Windows

### ISSUE THREAD

**Issue by akarel-mb** [mfontanini/presenterm#159]
On a Windows machine (Windows 11), if I include the yaml matter block and run `presenterm [path]` I get the following error:

```
invalid presentation metadata: deserializing from YAML containing more than one document is not supported
```

If I remove the block, the presentation renders as expected.

The following works...

```
Header
---

This is a test.

<!-- end_slide -->
```

But this does not...

```
---
title: Test
author: Test
---

Header
---

This is a test.

<!-- end_slide -->
```

**Comment by akarel-mb** [comment]
Forgot to add, I'm using presenterm version `0.4.1`

**Comment by mfontanini** [comment]
Thanks for the report! This is now fixed in master.
