### ISSUE TITLE
A basic HOWTO

### ISSUE THREAD

**Issue by Resonanz** [mfontanini/presenterm#163]
Please add a basic HOWTO to get the demo running.

```
git clone https://github.com/mfontanini/presenterm.git

cd presenterm

cargo build --release

./target/release/presenterm examples/demo.md
```

**Comment by mfontanini** [comment]
I'll add this later but yeah that, then `cargo run examples/demo.md`

**Comment by mfontanini** [comment]
Fixed in master, this is now in [here](https://mfontanini.github.io/presenterm/guides/basics.html#quick-start).
