### ISSUE TITLE
[Feature Request] A way to spread sub-titles or bullet points in the vertical direction

### ISSUE THREAD

**Issue by Davidyz** [mfontanini/presenterm#165]
In the current implementation, all content in a slide is crammed at the top of the page.

In the attached example, the three lines are seperated in the source markdown file. I wonder whether there's a way so that they are somewhat evenly distributed in the vertical direction so that there won't be such a huge blank space at the bottom. It'll be better if markdown sections and subsections (lead by hashtag symbols "`#`") can be respected.
![image](https://github.com/mfontanini/presenterm/assets/30951234/e15fa89e-4eb1-4889-82a0-bb6aff76174c)

**Comment by mfontanini** [comment]
I'll start by saying I doubt you'll ever get a good looking slide with that combination of a gigantic terminal and 3 lines of content :P. I do acknowledge this problem though, I'm just not sure what would be the ideal way to display this. e.g. where would you add the padding? Pad the first "in fact" line down by how much, then how much padding until the title? Then how much padding after that?  I don't think you can just evenly distribute them as that'll look bad in a different way IMO.

**Comment by Davidyz** [comment]
This is just a toy presentation to familiarise myself with this tool. I reckon that it might be difficult to implement an automatic mechanism to place the contents but would it be possible to add a parameterized command to allow manually adding blank lines, like
```
<!-- new_line 2 -->
```
for two blank lines, 
so that users can somehow control the spacing above a certain paragraph? At the moment there isn't even a way to "center" a paragraph in the vertical axis, which I find quite necessary when making slides.

**Comment by mfontanini** [comment]
> ```<!-- new_line 2 -->```

Yeah I've been thinking of this, it seems very useful.

> At the moment there isn't even a way to "center" a paragraph

I think I haven't documented it (and need to do that!) but there's a

```html
<!-- jump_to_middle -->
```

That jumps to the vertical center. Do note that if you already wrote something there, it will look like crap. My favorite (and really the only) use for this is to do something like

```markdown
blablabla

<!-- end_slide -->

<!-- jump_to_middle -->

Farming potatoes
===

<!-- end_slide -->
```

In order to create a nice "separator" slide that changes topics.

**Comment by mfontanini** [comment]
I created #167 to introduce the `new_lines` command. Does that work for you as a workaround?

**Comment by Davidyz** [comment]
Yes, this works for my issue. It would be nice if I could simply do `<!-- new_lines -->` (without an argument) for one single new line but the current implementation is totally good enough for me. Thanks for the lightning-fast reply & implementation.

**Comment by mfontanini** [comment]
Alright I merged the PR. There's 2 new commands:
* `new_lines: <number>` (you can also use `newlines`) that adds `<number>` new lines.
* `new_line` (you can also use `newline`) that adds a single new line.
