### ISSUE TITLE
`config.yaml` file is ignored on Windows

### ISSUE THREAD

**Issue by nagromc** [mfontanini/presenterm#180]
The `config.yaml` file is ignored on Windows unless I set the `HOME` environment variable to `%USERPROFILE%`. `%APPDATA%` should be preferred on Windows though.

Using the [`directories` crate](https://docs.rs/directories/latest/directories/) may help to load platform-specific paths (`%APPDATA%` on Windows for example).

presenterm v0.5.0

**Comment by mfontanini** [comment]
What's the exact path you would expect it to be in Windows? `%APPDATA%/presenterm/config.yaml`?

**Comment by nagromc** [comment]
Well, it’s up to your implementation, actually.

I think we should respect platform-specific paths:
* on Windows: `%APPDATA%/presenterm/config.yaml` (will point to `%USERPROFILE%/AppData/Roaming/presenterm/config.yaml`)
* on Linux: `~/.config/presenterm/config.yaml`
* on macOS: `~/Library/notSureOfThisPart/presenterm/config.yaml`

Or, if you want to keep it simple, `~/.config/presenterm/config.yaml` on every platform.

**Comment by mfontanini** [comment]
Thanks for the report! I verified this works as expected in windows (see PR for paths) but feel free to double check.

**Comment by nagromc** [comment]
It works as expected on Windows on my side. Thanks!
