### ISSUE TITLE
! rendered as \! when in a quote

### ISSUE THREAD

**Issue by sp3ctum** [mfontanini/presenterm#194]
Hi, just made a presentation with this awesome tool for work.

However, I think I found something odd. The following file seems to render incorrectly:

```md
> Hello!
```

<img width="507" alt="image" src="https://github.com/mfontanini/presenterm/assets/300791/ae6f9f69-cbbe-4a93-b823-24fc51e62a29">

I can't find a reason why the `\` character would be included. Any way to work around this?

**Comment by mfontanini** [comment]
Thanks for the report! This should be fixed in master, but let me know otherwise.

**Comment by sp3ctum** [comment]
Works perfectly! You are awesome - have a great day. 👍🏻
