### ISSUE TITLE
How I could achieve Elixir syntax highlighting?

### ISSUE THREAD

**Issue by zoedsoupe** [mfontanini/presenterm#20]
Actually, How I could achieve syntax highlighting for a language that appears not to be supported officially in Sublime Text (syntect).

**Comment by zoedsoupe** [comment]
I jsut found [syntect#168](https://github.com/trishume/syntect/issues/168) so there isn’t an option to highlight non supported languages by now. That so sad :/

**Comment by mfontanini** [comment]
Oh damn that sucks. `bat` seems to get around this issue though so there should be a workaround. I'll look into this later!

**Comment by mfontanini** [comment]
So yeah they seem to manage their own set of syntaxes. I'd be open to doing this, it'll just involve a good amount of plumbing but we should do it as we're otherwise quite limited in what languages we support

**Comment by mfontanini** [comment]
Hey @zoedsoupe I just pushed a draft PR (#21) that pulls in bat's syntax set file + adds elixir support. It's still in draft but it seems to work, can you check if this works for you?

![image](https://github.com/mfontanini/presenterm/assets/969090/d440ae5a-0d33-4c9f-98b6-a0354dd491a0)

**Comment by zoedsoupe** [comment]
Thats so cool! Good colors also! Now my workshop presentation is ready! Thank you for the effort. I tried to make a small PR too but didn’t seen to be sufficient. Thanks for the attention

<img width="830" alt="image" src="https://github.com/mfontanini/presenterm/assets/44469426/7eff508e-597e-43b5-b07e-286259baac08">

**Comment by mfontanini** [comment]
Nice that looks great! I'll try to add the remaining languages that bats supports tomorrow and get that merged.
