### ISSUE TITLE
Remote images no longer loading

### ISSUE THREAD

**Issue by sachinsenal0x64** [mfontanini/presenterm#213]
![image](https://github.com/mfontanini/presenterm/assets/127573781/f3dc7a4c-de99-4072-a07c-77b94100706d)

image-protocol = kitty-remote

**Comment by mfontanini** [comment]
That never worked and I don't think it's a good idea to do so. That makes presentations irreproducible and also can cause your live presentation to fail to load because of e.g. a shitty Internet connection.

**Comment by sachinsenal0x64** [comment]
Ok, thanks for the quick reply.
