### ISSUE TITLE
[Request] New line for multiple authors

### ISSUE THREAD

**Issue by NippleOfAnApe** [mfontanini/presenterm#225]
I want each author to be on a separate line. Is there a way to add an escape character ` author: 'Bob\nJim'` or use a newline tag?
```
author: Bob
<!-- new_line -->
Jim
```
Or maybe don't check for duplicate fields, so that multiple authors can be added like this
```
author: Bob
author: Jim
```

**Comment by mfontanini** [comment]
Maybe a new list like `authors: ["bob", "mike"]` could be added. Is doing `author: Bob and Mike` not good enough?

**Comment by NippleOfAnApe** [comment]
> Maybe a new list like `authors: ["bob", "mike"]` could be added. Is doing `author: Bob and Mike` not good enough?

I want to specify the responsibilities of each author.
```
Bob: data collection and analysis
Mike: pretending to be working
```
Putting it on the same line is a bit awkward, especially if I add more authors.

**Comment by mfontanini** [comment]
I just created #227 to address this. Any feedback before merging?

**Comment by NippleOfAnApe** [comment]
> I just created #227 to address this. Any feedback before merging?

Perfect. Love you
