### ISSUE TITLE
Handle suspending execution when receiving SIGTSTP signal (CTRL+Z)

### ISSUE THREAD

**Issue by timjk** [mfontanini/presenterm#237]
This would improve presentations by being able to pause execution, do something in the terminal, and then resume execution at the same location the presentation was at previously.

Currently I either shift between two terminals or, kill the process and start it over again - navigating to where I was in the presentation.

**Comment by mfontanini** [comment]
This makes sense. I'll see how to implement this, I guess presenterm `SIGTSTP`'ing itself should work.
