### ISSUE TITLE
[Feature request] Skipping footer on certain slides

### ISSUE THREAD

**Issue by aitor** [mfontanini/presenterm#238]
Hi there @mfontanini and the rest of the community!

I just recently discovered presenterm and I'm very much loving it. Congrats on making such a nice tool. 

I've been playing around with the different possible layouts and the footer configuration, and I was wondering if it would make sense for other people to skip the footer in certain slides (mostly the first and the last). 

I love having the footer as a subtle indication of progress during the talk, but it's kind of noisy when you are waiting to start the talk (projecting the intro slide) or, at the very end, in the Thanks/Q&A portion (the outro slide). I'd say those would be the main use cases, but I can see, too, how a specific slide that is already crowded with text or an ASCII diagram may benefit from skipping the footer. 

IMHO, it would be enough not to render the footer, the calculated interpolations for the template-based footer will remain untouched (e.g. even if the footer is not shown in the intro slide, it will still show 2/n in the next slide). 

The implementation could be based on a command or any special mark/comment that seems fit. If only the intro/outro are considered relevant, a setting in the footer frontmatter may be enough (`skip_on_intro`/`skip_on_outro`, etc.)

What do you think?

**Comment by mfontanini** [comment]
Thanks for the kind words! I think that makes sense. I think this could be added 2 forms:

* Skipping the footer in the intro slide should be a property of the theme.
* Skipping the footer in any slide should be a command, like `<!-- no_footer -->` .

Would that work for you?

**Comment by mfontanini** [comment]
@aitor I created #239 for this, can you have a look and let me know if that works for you?

**Comment by aitor** [comment]
I think that is perfect and will cover all the scenarios I need (and may think of)!
