### ISSUE TITLE
Script execution output does not render background color for tabs

### ISSUE THREAD

**Issue by carbon-steel** [mfontanini/presenterm#240]
# Problem
Tab character does not get correct background color in the output of script execution

![image](https://github.com/mfontanini/presenterm/assets/7697639/12cdc531-b4f0-4ab3-9730-0994ea8d4cc0)

# Presentation file
:arrow_right: ```bash +exec

:arrow_right: echo -e 'hi\they'

:arrow_right: ```

# Other info
OS: Fedora Linux
Presenterm version: 0.7.0
Presenterm theme: dark
Terminal: Kitty

**Comment by mfontanini** [comment]
Thanks for the report! This is fixed in master. I turned tabs into 4 spaces; lmk if you'd expect 2 and I can make this configurable.
