### ISSUE TITLE
Introduce a keymapping for quickly going through slides

### ISSUE THREAD

**Issue by carbon-steel** [mfontanini/presenterm#241]
I think it'd be handy, especially when editing presentations, to have a key I can press to click through slides without going through every single step within each slide. Instead, the key would show the beginning and ending states of each slide, skipping any intermediate states.

For example:
```
First slide
<!-- pause -->
a
<!-- pause -->
b
<!-- pause -->
c
<!-- pause -->
d
<!-- pause -->
e
<!-- end_slide -->
Second slide
<!-- pause -->
second slide end
```

Imagine I map this new function to the "n" key. When I start the presentation, I'll see the first line from the first slide.
* If I press "n", then the slide will show the first slide with all of its lines (a, b, c, d, e) revealed.
* If I press "n" again, then the second slide will appear with only its first line.
* If I press "n" again, then the second slide will appear with both of its lines shown.

The function doesn't have to be set to "n", or even be set to any key by default, but I think having the option to set this function to a key would be good.

Wdyt?

**Comment by mfontanini** [comment]
Thanks for the suggestion, I like it! I just implemented this. It's bound to `p` and `n` by default but you can override it via the [config file](https://mfontanini.github.io/presenterm/guides/configuration.html#key-bindings). The keys are `next_fast` and `previous_fast` (see [example config file](https://github.com/mfontanini/presenterm/blob/master/config.sample.yaml#L38-L45))
