### ISSUE TITLE
Support for multiple Authors

### ISSUE THREAD

**Issue by cyberme0w** [mfontanini/presenterm#263]
Hi there!

I've been playing around with `presenterm` and was planning on using it for some presentations I'll be doing in the future. One thing I would like to ask - as I was not able to find it in the documentation - is if it is currently possible to add multiple authors. This would be useful for all kinds of group presentations. My current workaround is to have a second slide listing the authors, but it'd be neat if that were supported out-of-the-box for the title screen.

In any case, thanks for a great program! I'm enjoying it quite a bit.

Cheers,
cyberme0w

**Comment by mfontanini** [comment]
This is already supported but wasn't documented. I just updated the docs to include this [here](https://mfontanini.github.io/presenterm/guides/basics.html#multiple-authors).

**Comment by cyberme0w** [comment]
Oh, nice. Thanks for the quick reply!
