### ISSUE TITLE
Is there a way to show flowchart ?

### ISSUE THREAD

**Issue by rishabhjain4** [mfontanini/presenterm#266]
I usually use Mermaid as it is supported by Gist tool on github.
Is it something in the roadmap for this feature or already present but not mentioned in the documentation?

I can acheive this using Latex flowchart and render it, but I was thinking of using flowchart with the pause functionality of the presenterm tool.

**Comment by mfontanini** [comment]
I think this is a great idea. This can work with the `+render` modifier like latex rendering works. I'll implement this soon, it shouldn't be a huge deal.

**Comment by PadenZach** [comment]
Mermaid support would be pretty killer here, since it's easier to learn than latex for most people.

Additionally, github supports mermaid so being able to have our markdowns rendered via github with mermaid also easy to convert into slides to show via presenterm would be very cool and powerful

**Comment by mfontanini** [comment]
I just created this PR (https://github.com/mfontanini/presenterm/pull/268). It would be nice if you could test it and let me know if anything looks odd. The mermaid cli is pretty slow so presenterm will hang for a bit on startup in a presentation that contains a mermaid snippet. This is something that can be improved separately.

**Comment by mikavilpas** [comment]
This is great. I was wondering about the same thing.

I need to create a presentation for work next week, and I think I can try this out then. No need to wait for me, of course - but I think an extra pair of eyes never hurts 🙂
