### ISSUE TITLE
Color output breaks line length

### ISSUE THREAD

**Issue by henryiii** [mfontanini/presenterm#272]
If a command produces colored output, it messes up the code box. It almost works, I think it's just counting the control sequence length incorrectly.

![Screenshot 2024-06-29 at 12 52 37 AM](https://github.com/mfontanini/presenterm/assets/4616906/8dee60a1-d2b8-475e-aba7-d19b32049a19)

**Comment by mfontanini** [comment]
I'll need to look at this, I never tried colored output and I'm not surprised it breaks. One issue for sure is that the escape sequences are considered normal text so that causes what you see in the image where the coloring of each line at the end is missing. But yes, there's clearly more going on.

**Comment by DrunkenToast** [comment]
If I find the time I wouldn't mind taking a jab at this issue.
I believe we can just escape ansi codes before calculating the padding, something like [this crate](https://docs.rs/strip-ansi-escapes/latest/strip_ansi_escapes/fn.strip_str.html) might do the job if we don't mind introducing dependencies.

**Comment by mfontanini** [comment]
If you'd like to give it a shot, go for it. The execution output is handled [here](https://github.com/mfontanini/presenterm/blob/master/src/processing/execution.rs#L142-L146) and the attribute you want to change should be [this one](https://github.com/mfontanini/presenterm/blob/master/src/processing/execution.rs#L75). Ideally we'd compute the real length only once and then store it so [this thing](https://github.com/mfontanini/presenterm/blob/master/src/processing/execution.rs#L18) would need to have more than just a string.

**Comment by mfontanini** [comment]
This was fixed in #315.

**Comment by henryiii** [comment]
Thanks!

**Comment by henryiii** [comment]
That's a link to an issue, by the way, not a PR.
