### ISSUE TITLE
Pre-render mermaid for diagrams

### ISSUE THREAD

**Issue by kemelzaidan** [mfontanini/presenterm#277]
It would be awesome if presenterm supported mermaid for diagrams, just like it does for latex and typst: https://mermaid.js.org.

Github and Gitlab supports it :+1: 

```mermaid
        graph TD
        A[Client] --> B[Load Balancer]
        B --> C[Server01]
        B --> D[Server02]
```

Thanks for the awesome app!

**Comment by mfontanini** [comment]
This is actually already supported (see original issue #266), it's just not released yet. You can build the master branch from source and you'll have access to it. See the PR (#268) that introduced this to get an explanation of how it works. I will document this properly once it's included in the next release, which will hopefully go out soon.

**Comment by kemelzaidan** [comment]
That's great! Thanks! :+1:
