### ISSUE TITLE
Visual indication for executable code snippets

### ISSUE THREAD

**Issue by mfontanini** [mfontanini/presenterm#278]
I'm creating this to see if someone has any ideas on how to do this: executable snippets should show _something_ different that lets you realize they're executable. I can't think of a good way of doing this; IMO this should be:

* Noticeable fairly easily, at least if you know what you're looking for (e.g. some utf8 icon somewhere in the code snippet).
* Non intrusive. e.g. I don't want the indication to be distracting to the audience of the presentation.
* Looks good.

I tried to put a little gear utf8 character in the bottom right corner of the code snippet but it doesn't look good. It is noticeable and non intrusive IMO but it doesn't look good.

A title on the top or bottom that says something like "executable snippet" would be noticeable but would be very intrusive to me.

Anyhow, if anyone has any ideas, please chime in.

**Comment by marianozunino** [comment]
@mfontanini Matias, first of off: great project, I'm using it heavily! I would love to contribute, but my rust skills are `null`.

So here's my suggestion for this feature:

- Without `+line_numbers`
```c
 ▶ #include <stdio.h>
  
   int main() {
       int arr[3] = {1, 2, 3};
       int value = arr[5];  // Accessing an out-of-bounds index
       return 0;
   }
```

- With `+line_numbers`

```c
 ▶ #include <stdio.h> // It replaces the line number 0
 1
 2 int main() {
 3     int arr[3] = {1, 2, 3};
 4     int value = arr[5];  // Accessing an out-of-bounds index
 5     return 0;
 6 }
```

- Maybe we can configure/replace the `play` icon using something like:
>  \`\`\`c +line_numbers +exec +exec_icon{▶|bg|fg}
>  \`\`\`
- If not +exec is visible, it won't do anything

**Comment by mfontanini** [comment]
Thanks for the kind words! Very nice, I like it. My idea is to make this indication configurable so it doesn't have to be forced to be this, there can be some `decoration: play_button` or something in the theme.

**Comment by calebdw** [comment]
@mfontanini, 

You already show a bar for the execution status, what if you just always displayed it with a status of `pending`/`not started` instead of it suddenly appearing when the execution starts?


![image](https://github.com/user-attachments/assets/8ce34e0a-d9d8-46e0-b650-7bc076fad6bc)

FYI, it looks like the execution block is slightly smaller than the status bar...

**Comment by DrunkenToast** [comment]
I think the above solution is fine and clear, if you want to continue with the icon indication then I suggest the following:
- Make it configurable with simply a text field, users can adjust it with unicode characters/emoji's/text themselves.
- Often times websites have a play button in the right top corner like so: <img width="845" alt="image" src="https://github.com/user-attachments/assets/df21eef1-93a2-49e4-8242-e4b74e587319">
    - Perhaps put the icon inside the padding corner if there is padding and otherwise just the last character. Seems like a bit of a hassle to implement compared to the line_number approach however since prefix etc already exists, and people might think the play button is clickable.
