### ISSUE TITLE
Dim non-highlighted code

### ISSUE THREAD

**Issue by DrunkenToast** [mfontanini/presenterm#285]
In code-blocks you can mark the lines that should get highlighted, however it looks somewhat off. It looks as if the highlighting is simply broken on the non-highlighted portions, they still have a lot of contrast.

Is it possible to theme it so that the non-highlighted portions of the code-block are dimmer/gray instead? This will lead to better focus on the highlighted portions I believe.

**Comment by mfontanini** [comment]
Yeah you're right, the non highlighted lines still stand out too much. I'll have a look soon. Thanks for the report!

**Comment by mfontanini** [comment]
This is fixed in #287. Thanks for the suggestion, this looks so much better now :pray:

**Comment by DrunkenToast** [comment]
Looks amazing! Thanks for the quick implementation! 🚀
