### ISSUE TITLE
Can not show properly on Mac Terminal

### ISSUE THREAD

**Issue by shenxiangzhuang** [mfontanini/presenterm#294]
It seems I can not got right format on Mac. What's the possible reasons about this problem? I try to set the profile of the terminal into default, but it doesn't fix this.

## Version
```bash
❯ presenterm -V        
presenterm 0.7.0
```

![image](https://github.com/user-attachments/assets/a63f4274-aa23-467e-94c7-d4ad9fd66aed)

**Comment by mfontanini** [comment]
Are you using iterm2? Is this using the default presenterm theme?

**Comment by shenxiangzhuang** [comment]
> Are you using iterm2? Is this using the default presenterm theme?

No, I'm using the build-in terminal of MacOS with default profile setting. And, yes, I use the default presenterm theme.

By the way, I test presenterm on iterm2 and other terminals(like warp and some ide's build-in terminals),  and there is no problem. So I think the problem is most likely related to the MacOS build-in terminal that I use, rather than presenterm...But I still wondering how this happened :)

**Comment by mfontanini** [comment]
My guess is that terminal doesn't support 24 bit colors. Can you run `presenterm --theme terminal-dark path-to-your-presentation.md`? That theme uses your terminal's colora rather than 24 bit ones so if that's the case it should work.

**Comment by shenxiangzhuang** [comment]
> My guess is that terminal doesn't support 24 bit colors. Can you run `presenterm --theme terminal-dark path-to-your-presentation.md`? That theme uses your terminal's colora rather than 24 bit ones so if that's the case it should work.

Thanks for your suggestion! The `--theme terminal-dark` option works fine, except the code block:
![image](https://github.com/user-attachments/assets/521e4343-2523-4f89-a93c-83ef238d9f61)

And I try `--theme terminal-light` option, which works much better:
![image](https://github.com/user-attachments/assets/24c3511e-14eb-44ea-ac6a-074804bed42f)


Thank you again for your timely reply!
