### ISSUE TITLE
Allow support for `sh` for shell syntax

### ISSUE THREAD

**Issue by TanishqSingla** [mfontanini/presenterm#3]
## Overview 
`sh` is note supported in codeblocks

## Current Behaviour
If we try to use `sh` while creating a code block

E.g
<code>
\`\`\`sh
cat hello world
\`\`\`
</code>
Throws this error.

```
thread 'main' panicked at /home/eyepatch/.cargo/registry/src/index.crates.io-6f17d22bba15001f/presenterm-0.1.0/src/render/highlighting.rs:31:69:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Suggested solution
Since `bash` works perfectly fine, it would be convenient to have `sh` as an alias to `bash`

**Comment by mfontanini** [comment]
Thanks! This was a typo, it was supposed to work with `sh`. If you pull the latest source from the repo and run it, it should work. I added tests so this doesn't happen again.
