### ISSUE TITLE
Running code from CWD

### ISSUE THREAD

**Issue by DrunkenToast** [mfontanini/presenterm#322]
Currently code is ran from the /tmp directory, however this leads to unexpected results.

For instance a repository with slides might run scripts from that repository, however it will not be able to relatively refer to those scripts and will need to define the paths absolutely.

Now the problem arises when another person wants to run these slides, since the absolute paths would be incorrect.

I am not sure if this would cause any security issues, the slides are still explicit about what they do, they now just behave like any other executable and run from with the context of that cwd where the presentation was started.

Reasons why we would want this:
- Include other files in script block to focus on the important code, highlight in the codeblock
- Include libraries for languages such as Javascript
- Behaves as the writer/new users would expect

Not sure why we wouldn't want this but open to discuss.

---
```bash
pwd
```
`cd ~/slides`
`presenterm +x slides.md`

Expected behaviour:
`/home/<user>/slides`

Current behaviour:
`/tmp/<hash>`

**Comment by DrunkenToast** [comment]
> You beat me to opening this!

Yes! I won the race! :rocket:
I have implemented something quickly in #323, so you can check that out if you'd like!

**Comment by mfontanini** [comment]
Nice, thanks!

**Comment by glfharris** [comment]
Just to add that this fix doesn't seem to apply for the python path & imports. Have to do something like the following for `/path/to/folder/local_module':

```python +exec
import sys
sys.path.insert(0, '/path/to/folder/')
import local_module
```
