### ISSUE TITLE
feat: add content from files into codeblocks

### ISSUE THREAD

**Issue by DrunkenToast** [mfontanini/presenterm#326]
Use cases:
- Keep the markdown file itself less cluttered
- Refer to a file in a codebase, you won't need to maintain it in 2 places

**Comment by calebdw** [comment]
Related to #307

**Comment by DrunkenToast** [comment]
> Related to #307

Oh oops! I have implemented something like this but it only related to codeblocks. See #327.

**Comment by DrunkenToast** [comment]
Closing as duplicate for #307
