### ISSUE TITLE
Line-wrapping on executeable code block will cause the status line to wrap

### ISSUE THREAD

**Issue by DrunkenToast** [mfontanini/presenterm#343]
If your code block is too big and wraps, the status line will take the original width and wrap as well, even though it could fit:
![image](https://github.com/user-attachments/assets/1f5c13bf-14b4-4254-8530-45b5f8f9e5f1)
![image](https://github.com/user-attachments/assets/1644bf54-4184-49b3-ad6a-231416394c13)

Expected behaviour is for the line to get shorter and not wrap.

**Comment by mfontanini** [comment]
This is fixed in https://github.com/mfontanini/presenterm/pull/353. There's still a little quirk when you're resizing where the bar is a little longer than it should but at least it never wraps around.
