### ISSUE TITLE
Pausing in a different order is not possible

### ISSUE THREAD

**Issue by DrunkenToast** [mfontanini/presenterm#346]
Currently you can set breaks at certain points in your markdown but this limits you in which order things might appear.
For instance you might have an image on the right side, but now you can not pause inbetween text on the left if you want to keep the image visible.

I am not certain of a nice API for this but something like an optional order priority for pausing with pause blocks?

**Comment by mfontanini** [comment]
I just added an example of how to use columns/pauses to do what I think you want in https://github.com/mfontanini/presenterm/pull/348. Let me know if this doesn't address that tho. Basically nothing forces you to first define the contents of the left column and then the right one. You an define the right one and then use pauses on the left column.

**Comment by DrunkenToast** [comment]
Ah, derp, I didn't think of that for some reason. It does indeed resolve most of my situations, thanks! (although it *feels* wrong writing in a different direction :P)
However, in one of my presentations I had a situation where I would've liked to alternate pauses between columns which isn't possible I believe.

I completely understand that this is way too niche however and that it's closed as won't fix for simplicity's sake.

Example:
I have a bullet list that I pause certain sections of and then on the side some graphics/codeblocks appear related to each part that I reveal.

Copy-pasting works as well ofc ;) but it would be nice if you could do something like `<!-- start/end_pause: <priority number> -->` for prioritizing sections to pause.

**Comment by mfontanini** [comment]
> However, in one of my presentations I had a situation where I would've liked to alternate pauses between columns which isn't possible I believe.

I thought this was possible in another way but apparently not. How this could work without adding anything new is you could be allowed to use `<!-- column: 1 -->` multiple times and it continue where you left off. So you could technically go to column 0, pause, go to column 1, pause, go back to column 0, etc. It will potentially be a bit odd for you but that will let you build basically any sort of column/pause combo. Right now using `column: 0` if you've already set it will make the cursor go back to the beginning of that column which is wrong/unexpected. I'd need to double check to make sure this doesn't cause any issues, but I think it should be doable. In the end it wouldn't be super pretty to write but it would give everyone the building blocks to pause however they want.

**Comment by DrunkenToast** [comment]
I think that's a fair compromise, it is fairly niche usecase and if the documentation mentions it then I think discoverability wouldnt be too bad.
