### ISSUE TITLE
Tabs in codeblocks behave unexpectedly

### ISSUE THREAD

**Issue by DrunkenToast** [mfontanini/presenterm#355]
![image](https://github.com/user-attachments/assets/f4fb7cc8-1bab-4861-afe5-fc928c7fec5a)

In this example the second function (main) uses tabs instead of spaces.

**Comment by mfontanini** [comment]
Ughhhhhh. I'll replace it with 4 spaces. Thanks!

**Comment by DrunkenToast** [comment]
> Ughhhhhh.

I felt that.
