### ISSUE TITLE
Option to remove or replace slide progressbar

### ISSUE THREAD

**Issue by dheerajshenoy** [mfontanini/presenterm#357]
I looked everywhere in the documentation if there was a way to interact with the slide progressbar shown at the bottom. It would be really nice if there was a way to either remove it completely or replace it or maybe have different kind of progress indicator, like current (slide number / total slides). I really love presenterm, thanks for creating this.

**Comment by dheerajshenoy** [comment]
I found a section for this in the documentation [here](https://mfontanini.github.io/presenterm/guides/themes.html#template), the problem is solved i suppose. But then, if there was a flag like --no-progressbar or something like that, it would be cool.

**Comment by mfontanini** [comment]
I turned the default footer into a template style footer in #358.
