### ISSUE TITLE
Font size configuration support

### ISSUE THREAD

**Issue by joel-olazagasti** [mfontanini/presenterm#37]
It's totally possible that I've missed it, but I didn't see any way to configure font sizes. If it already doesn't exist, is it on the roadmap/something you want to support at all? If so, I'd be happy to contribute to the feature, maybe with the smallest amount of direction 🙂

**Comment by mfontanini** [comment]
Do you mean a global font size? You should be able to zoom in your terminal, e.g. kitty uses `control +` and `control -` for this. 

I don't think you can have different font sizes simultaneously, in case that's what you're asking for, as the terminal has a number of rows and every character fits in only one. So you can't have one row with font size 12 and the next with 15 AFAIK.

**Comment by joel-olazagasti** [comment]
Ahh, yeah I didn't consider terminal limitations on granularly assigning font sizes. That makes sense. Thanks! Was just a nice-to-have anyways (I wanted to make the title bigger)

**Comment by mfontanini** [comment]
Ah yeah, that would be nice but unfortunately it's a general terminal limitation.
