### ISSUE TITLE
Support reStructuredText input

### ISSUE THREAD

**Issue by toastal** [mfontanini/presenterm#378]
Markdown is far too limiting in features set, but reStructureText is more robust with built-in features (at least for CommonMark, else it is yet another Markdown fork with questionable compatibility with other renderers)

* Built-in metadata  instead of ad-hoc YAML
* Built-in file includes for organization
* Admonition/callouts
* Figure syntax
* Image sizing options
* Citations for quotations (block quotes)
* Footnotes
* Definition lists
* Table of contents support (could be used for shortcuts)

**Comment by mfontanini** [comment]
This tool takes markdown as input and there's no plans to add any other format, in particular because markdown (along with its support for html comments/tags) is enough for what this tool tries to do.
