### ISSUE TITLE
unflaging `strict_front_matter_parsing`, but presenterm remains strict

### ISSUE THREAD

**Issue by thisismygitrepo** [mfontanini/presenterm#380]
I'm setting `strict_front_matter_parsing` to `false`, however, it still complains because it doesn't understand one line.

```markdown
---
marp: true
title: Ethics Concers on AI in ED
author: Alex Al-Saffar

---
<!-- class: invert -->

```

I get this error:

```shell

Error loading presentation:

                           error parsing command at line 8: unknown variant
                           `class`, expected one of `pause`, `end_slide`,
                           `new_line`, `new_lines`, `column_layout`, `column`,
                           `reset_layout`, `jump_to_middle`,
                           `incremental_lists`, `no_footer`
```

Can we please make it more tolerant of such non-markdown syntax that other tools rely on. Cross compatibility with zero editing will encourage more users to migrate.

Thanks

**Comment by mfontanini** [comment]
That option affects from matter parsing so it's entirely unrelated to the HTML comment you're using. You need to set [this option](https://mfontanini.github.io/presenterm/guides/configuration.html#command_prefix) if you want to differentiate between commands for this tool and commands for other ones.
