### ISSUE TITLE
Using the no background and exec replace flags on codeblocks doesn't seem to work

### ISSUE THREAD

**Issue by GV14982** [mfontanini/presenterm#381]
Hi there, love this project!

I'm currently trying to use the `+no_background` and `+exec_replace` options but it doesn't seem to be removing the background...

Here is my codeblock:
\```bash +no_background +exec_replace
figlet -f starwars "Vim Motions" | lolcat -f
\```

Is this not supported? The docs mention it [here](https://mfontanini.github.io/presenterm/guides/code-highlight.html#showing-a-snippet-without-a-background).

**Comment by mfontanini** [comment]
Thanks for the report! I knew this was missing when implementing `no_background` but ended up forgetting to get back to it. This is now fixed!

**Comment by GV14982** [comment]
Awesome, thanks so much for the quick turnaround!

![image](https://i.giphy.com/osjgQPWRx3cac.webp)
