### ISSUE TITLE
ignore vim modeline

### ISSUE THREAD

**Issue by astephanh** [mfontanini/presenterm#392]
can't use html comment for vim modeline

test.md 

```markdown

---
title: Presentation
author: Author
theme:
  name: terminal-dark
---

<!-- vim: set fenc=utf-8 spell spl=en: -->
```

start presentation error:

```sh
 Error loading presentation:

                      error parsing command at line 8: unknown
                      variant `vim`, expected one of `pause`,
                      `end_slide`, `new_line`, `newline`,
                      `new_lines`, `newlines`, `column_layout`,
                      `column`, `reset_layout`,
                      `jump_to_middle`, `incremental_lists`,
                      `no_footer`

```

**Comment by mfontanini** [comment]
You can set a command prefix for now (see [docs](https://mfontanini.github.io/presenterm/guides/configuration.html#command_prefix)) to disambiguate between vim commands and presenterm's. I will fix this tho so vim prefixed commands are skipped given I presume you're not the only one with this issue.

**Comment by astephanh** [comment]
Hi, 

thx. that is working.
