### ISSUE TITLE
Export PDF // choose Font Size

### ISSUE THREAD

**Issue by astephanh** [mfontanini/presenterm#394]
Hi, 

is there a way to change the fontsize before exporting to pdf / changing the tmux size? I have a rather large screen. A PDF export is using very small fonts, which makes it hard to read the pdf on other systems.

**Comment by mfontanini** [comment]
The generated PDF will respect the size of the terminal you're running the export from, so if your terminal size is small it should end up having a larger font. If you shrink the terminal, does that help?

**Comment by astephanh** [comment]
Ok. i understand. so basically i'd need to setup my terminal in advance to create the pdf with the dimension and fontsize that i like.

**Comment by mfontanini** [comment]
Exactly. Closing this issue, but reopen if resizing doesn't fix it.
