### ISSUE TITLE
Support C# language code execution

### ISSUE THREAD

**Issue by giggio** [mfontanini/presenterm#398]
According to the [docs](https://mfontanini.github.io/presenterm/guides/code-highlight.html#executing-code-blocks), C# is not yet supported.

There are several tools one can use to execute C# files directly, in a cross platform way. An officially supported one, from the .NET team, is [dotnet-script](https://github.com/dotnet-script/dotnet-script).

**Comment by mfontanini** [comment]
Can you make a PR adding it to the [executors file](https://github.com/mfontanini/presenterm/blob/master/executors.yaml)? I imagine it will look like the [kotlin one](https://github.com/mfontanini/presenterm/blob/master/executors.yaml#L41-L45) or any scripting language. Just add a `c#` entry and that should do it

**Comment by giggio** [comment]
@mfontanini done, at #399.
