### ISSUE TITLE
Query for support instead of hardcoding terminal emulators which support the Kitty Image Protocol

### ISSUE THREAD

**Issue by 00-kat** [mfontanini/presenterm#408]
This will remove the need for new PRs (e.g. #405) every time a new terminal emulator needs to be added to [the hardcoded list](https://github.com/mfontanini/presenterm/blob/5e651f636037c658e21c3cea8b7cf6b7b6ccae25/src/media/emulator.rs#L71).  Relevant docs: https://sw.kovidgoyal.net/kitty/graphics-protocol/#querying-support-and-available-transmission-mediums.

**Comment by mfontanini** [comment]
This is already being done, a few more cases were added in #406 that made it work as expected. I don't think #405 was necessary now but I created it before the changes in #406 so it was needed at the time.
