### ISSUE TITLE
When using overrides without specifying a footer, footer theme is set to default

### ISSUE THREAD

**Issue by rmartine-ias** [mfontanini/presenterm#51]
When presenting a file with overrides set, the lack of a footer key is interpreted as an [empty footer](https://github.com/mfontanini/presenterm/blob/a2d7157e44664d4fe7522a7ec4e87a52d1f16730/src/theme.rs#L315), which is parsed as the default footer, which overrides the theme's footer.

Reproduction:
1. `presenterm examples/demo.md` (see progress bar)
2. Edit header of `demo.md` to include:
   ```yaml
   theme:
    override:
      default:
   ```
 3. `presenterm examples/demo.md` (see 1/9 in footer)

**Comment by mfontanini** [comment]
Thanks for the report! This should be fixed now, but let me know otherwise.
