### ISSUE TITLE
Images look small when text font is high

### ISSUE THREAD

**Issue by GaetanLepage** [mfontanini/presenterm#77]
I understood that images are checked to fit in the width of the presentation.
However, the more I zoom (increase my terminal font size), the more the image shrinks.
At the font size I feel confortable with regarding text, my image looks absolutely tiny. It then only takes a fraction of the available space. I tried resizing the image to various sizes but it didn't help.

**Comment by GaetanLepage** [comment]
Precision: this behavior appears in the `foot` terminal (using `sixel`) but not in `kitty`.

**Comment by mfontanini** [comment]
I'll look into this. AFAIK the crate we use to render images has "experimental" support for sixel so it's possible whatever is necessary to resize the image using sixel isn't there.

**Comment by GaetanLepage** [comment]
Ok understood ! I will use kitty then.
Thanks for your answer :)

**Comment by mfontanini** [comment]
Yeah unfortunately I think that's the easiest solution at this point.
