### ISSUE TITLE
Possible to switch on slide numbers?

### ISSUE THREAD

**Issue by janroden** [mfontanini/presenterm#8]
Is there a possibility to show slide numbers? 
So the audience can refer to them when they ask questions...

Thanks!

**Comment by mfontanini** [comment]
This is already possible. See the [docs on themes](https://github.com/mfontanini/presenterm/blob/master/docs/themes.md#template). So for example you can do:

```markdown
---
author: Matias
theme:
    override:
        footer:
            style: template
            left: "{author}"
            right: "{current_slide} / {total_slides}"
            center: "2023-10-18"
                
---

# Hi mom
```

Which would look like 
![image](https://github.com/mfontanini/presenterm/assets/969090/be648d65-1ac6-46d8-847d-d2c63e7e8ced)

You can also create your own theme and [point to it](https://github.com/mfontanini/presenterm/blob/master/docs/themes.md#by-path) in your slide. e.g. copy `themes/dark.yaml`, edit the footer bit with the thing above and point to it in your presentation by using

```
theme:
  path: /home/me/theme.yaml
```

**Comment by janroden** [comment]
That's awesome! Thanks a lot :)
