### ISSUE TITLE
Workaround for making text appear in the middle of the page?

### ISSUE THREAD

**Issue by nshern** [mfontanini/presenterm#84]
Is there a workaround for making text appear in the middle of the page instead of at the top?

**Comment by mfontanini** [comment]
There's no feature for this implemented yet. What we could do is add a comment command like `<!-- jump_to_middle -->` or something which moves the cursor to the middle. This means the cursor would start there so if you had 10 lines it would look like the first one is at the middle and the rest of them go from there. e.g. it wouldn't mean "vertically center" but more like "start at the vertical center". Would that work?

**Comment by nshern** [comment]
> There's no feature for this implemented yet. What we could do is add a comment command like `<!-- jump_to_middle -->` or something which moves the cursor to the middle. This means the cursor would start there so if you had 10 lines it would look like the first one is at the middle and the rest of them go from there. e.g. it wouldn't mean "vertically center" but more like "start at the vertical center". Would that work?

Yes, I think this would work!

**Comment by mfontanini** [comment]
I just created a branch for this. Does this make sense to you?

[![asciicast](https://asciinema.org/a/4Qp8JHoTSZNuxxm4cp0kunt40.svg)](https://asciinema.org/a/4Qp8JHoTSZNuxxm4cp0kunt40)

**Comment by nshern** [comment]
I think it works great :)

**Comment by mfontanini** [comment]
Sweet, merged then!
